name: clean_framework_example
description: Sandbox with example of all components from clean framework
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  clean_framework_legacy:
    path: ../

  intl: ^0.18.1

flutter:
  uses-material-design: true
