name: clean_framework_legacy
description: Clean Architecture components library, inspired on the guidelines created by Uncle Bob.
version: 1.0.0
homepage: https://acmesoftware.com/
repository: https://github.com/AcmeSoftwareLLC/clean_framework_legacy

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: '>=3.10.6'

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_riverpod: ^2.3.6
  equatable: ^2.0.5
  http: ^1.1.0
  meta: ^1.9.1
  provider: ^6.0.5
